feat(CORSO-17)Update Order Progression
DylanBrass/Corso-Website pull request #123
Opened 2024-02-11 22:22 UTC by DenisaNicoletaH

JIRA: https://champlainsaintlambert.atlassian.net/browse/CORSO-17

## Context:
Allows admins to update, leave progression notes, update service and update estimation hours as well as hours worked.
## Changes

- Over 90% Jacoco Testing
- Added OrderProgressionPage.tsx
- Added OrderProgressionPage.css
- Send email to clients when order is updated and completed.
- Modified ViewSpecificOrderAdmin.tsx

## Before and After UI (Required for UI-impacting PRs)

**No before page

**After: 
![image](https://github.com/DylanBrass/Corso-Website/assets/91993350/b1fe2c3c-acee-4b62-92af-16a8c19f5677)

2024-02-11 23:04 UTC, DylanBrass requested changes
This is all I found that I would like fixed

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_fe/src/App.tsx
> +                        <Route path="/manage/completedOrder/:orderId" element={<OrderProgressionPage/>}/>
This naming does not make sense to me.

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_fe/src/App.tsx
> +                        <Route path="/manage/updateProgression/:orderId" element={<OrderProgressionPage/>}/>
This seems to be duplicate

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +                "Your Company Name";
Please put Corso and not Company name, and we also need french and english

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +        Status newcompletedStatus = Status.COMPLETED;
for the sake of pure optimization, set the variable after the null check

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +        }
Maybe adding a check that the order has at least an hour worked on it.

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/presentationlayer/OrderProgressionRequest.java
> +    }
This constructor is probably not necessary

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/resources/templates/UpdateOrder.html
> +                    <td><b>Name :</b><span th:text="${name}"></span></td>
the < / b > looks off

2024-02-11 23:04 UTC, DylanBrass commented on corso_website_springboot/src/main/resources/templates/UpdateOrder.html
> +                    <td><b>Name :</b><span th:text="${name}"></span></td>
Same thing here for < / b >

2024-02-12 00:54 UTC, DenisaNicoletaH commented on corso_website_fe/src/App.tsx
> +                        <Route path="/manage/completedOrder/:orderId" element={<OrderProgressionPage/>}/>
I removed it since I wasn't using it

2024-02-12 00:55 UTC, DenisaNicoletaH commented on corso_website_fe/src/App.tsx
> +                        <Route path="/manage/updateProgression/:orderId" element={<OrderProgressionPage/>}/>
I removed the one that wasn't being used, but kept this one since it is used

2024-02-12 00:56 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +                "Your Company Name";
I have fixed that in my current push.

2024-02-12 00:59 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +        }
I did this change in my current push. I did so that the admins need to have at least 1 hour worked in order for the order to be completed

2024-02-12 01:00 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/presentationlayer/OrderProgressionRequest.java
> +    }
I need it since I am using it in ServiceImpl otherwise my code fails since I need to get the progress Information .

2024-02-12 01:01 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/resources/templates/UpdateOrder.html
> +                    <td><b>Name :</b><span th:text="${name}"></span></td>
I fixed this issue recently.  The </b> is fine and works as expected.

2024-02-12 01:01 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/resources/templates/UpdateOrder.html
> +                    <td><b>Name :</b><span th:text="${name}"></span></td>
I fixed this issue recently.  The </b> is fine and works as expected

2024-02-12 01:19 UTC, DenisaNicoletaH commented on corso_website_springboot/src/main/java/com/corso/springboot/Order_Subdomain/businesslayer/OrderServiceImpl.java
> +        Status newcompletedStatus = Status.COMPLETED;
I just fixed it, let me know if you see any errors.

2024-02-12 01:33 UTC, DylanBrass commented on corso_website_springboot/src/main/resources/templates/UpdateOrder.html
> +                    <td><b>Name :</b><span th:text="${name}"></span></td>
The < / b > is still there ?

2024-02-12 01:33 UTC, DylanBrass commented on corso_website_fe/src/App.tsx
> +                        <Route path="/manage/updateProgression/:orderId" element={<OrderProgressionPage/>}/>
I meant delete

2024-02-12 01:35 UTC, DylanBrass approved these changes

2024-02-12 01:43 UTC, Mila5847 approved these changes
Feature looks good and tested, thank you for putting the localization too

2024-02-12 01:57 UTC, merged